--SCHEMA CREATION SQLs for the list of entities.

--COMPANY
CREATE TABLE COMPANY(
 COMPANY_ID VARCHAR2(20) UNIQUE PRIMARY KEY,
 COMPANY_NAME VARCHAR2(30) UNIQUE NOT NULL,
 YEAR_OF_INCLUSION VARCHAR2(10) NOT NULL
);

--PERSON
CREATE TABLE PERSON(
 PERSON_ID VARCHAR2(20) UNIQUE PRIMARY KEY,
 NAME VARCHAR2(30) UNIQUE NOT NULL,
 AGE VARCHAR2(10),
 NATIONALITY VARCHAR2(20),
 GENDER CHAR
);

--PERSON COMPANY
CREATE TABLE PERSON_COMPANY(
 PERSON_ID VARCHAR2(20) UNIQUE PRIMARY KEY,
 COMPANY_ID VARCHAR2(30) UNIQUE NOT NULL,
 YEAR DATE,
 SALARY VARCHAR2(20) 
);

--COMPANY FINANCE
CREATE TABLE COMPANY_FINANCE(
 COMPANY_ID VARCHAR2(10),
 START_DATE DATE,
 END_DATE DATE,
 STOCK_PRICE 
);

--PROFESSIONAL PERSON
CREATE TABLE PROFESSIONAL_PERSON(
 PERSON_ID VARCHAR2(20),
 COMPANY_ID VARCHAR2(20),
 POSITION VARCHAR2(20),
 START_DATE DATE,
END_DATE DATE
);

--COMPANY ACQUISITIONS & PRESS NEWS
CREATE TABLE COMPANY_NEWS(
 COMPANY_ID VARCHAR2(20),
 START_DATE DATE,
 END_DATE DATE,
 NEWS STRING,
 TYPE STRING
);

--AFFILIATIONS & MISC VALUES
CREATE TABLE PERSON_TRAITS(
 PERSON_ID VARCHAR2(20),
 START_DATE DATE,
 END_DATE DATE,
 AFFILIATION STRING,
 ACHIEVEMENT STRING 
);
